api = "0.9"

[buildpack]
id = "heroku/go"
version = "0.1.5"
name = "Heroku Go"
homepage = "https://github.com/heroku/buildpacks-go"
keywords = ["go", "golang", "heroku"]
clear-env = true

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[metadata]

[metadata.release]

[metadata.release.image]
repository = "docker.io/heroku/buildpack-go"
