[package]
name = "heroku-inventory-utils"
rust-version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
semver = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
toml = "0.8"
