name: Update Inventory
on:
  workflow_dispatch:
  schedule:
    - cron: '00 4 * * 1-5'

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  update-go-inventory:
    name: Update Go Inventory
    runs-on: pub-hk-ubuntu-24.04-ip
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ vars.LINGUIST_GH_APP_ID }}
          private-key: ${{ secrets.LINGUIST_GH_PRIVATE_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Update Rust toolchain
        run: rustup update

      - name: Rebuild Inventory
        id: rebuild-inventory
        run: |
          delimiter="$(openssl rand -hex 8)"
          {
            echo "msg<<${delimiter}"
            cargo run --bin update_inventory buildpacks/go/inventory.toml buildpacks/go/CHANGELOG.md
            echo "${delimiter}"
          } >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          title: "Update Go Inventory"
          commit-message: "Update Inventory for heroku/go\n\n${{ steps.rebuild-inventory.outputs.msg }}"
          committer: ${{ vars.LINGUIST_GH_APP_USERNAME }} <${{ vars.LINGUIST_GH_APP_EMAIL }}>
          author: ${{ vars.LINGUIST_GH_APP_USERNAME }} <${{ vars.LINGUIST_GH_APP_EMAIL }}>
          branch: update-go-inventory
          body: "Automated pull-request to update heroku/go inventory:\n\n${{ steps.rebuild-inventory.outputs.msg }}"

      - name: Configure PR
        if: steps.pr.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: gh pr merge --squash --auto "${{ steps.pr.outputs.pull-request-number }}"
